server:
  port: 8090
  servlet:
    context-path: /auth-server

spring:
  application:
    name: auth-server
  # 数据库
  datasource:
    url: jdbc:mysql://172.28.19.88:3306/cltest?useSSL=false
    username: dhome
    password: dhome
    driver-class-name: com.mysql.jdbc.Driver
#Mybatis Config
mybatis:
  typeAliasesPackage: com.server.auth.dao
  mapperLocations: classpath:mybatis/**/*.xml